using System.Net;
using System.Net.Http.Json;
using MediatR;
using Explain.Api.Common;
using Explain.Api.Infrastructure.Storage;

namespace Explain.Api.Features.Interviews.SpeakVoice;

// Same ElevenLabs-proxy-plus-blob-cache pattern as Lessons/ReadAloud/ReadAloudHandler.cs, one
// utterance at a time (no chunking — interview lines are short enough not to need it). This is
// the fix for the interview room's Sarah/James/Mike voices previously being generated by a
// direct browser->ElevenLabs call with VITE_ELEVENLABS_API_KEY baked into the public bundle —
// same class of exposure as the earlier OpenAI incident, just never fixed for this call site.
public class SpeakVoiceHandler(
    TtsCacheService cache,
    IHttpClientFactory httpFactory,
    IConfiguration config,
    ILogger<SpeakVoiceHandler> logger)
    : IRequestHandler<SpeakVoiceCommand, Result<SpeakVoiceDto>>
{
    private const string Model = "eleven_turbo_v2";

    // Same transient-status retry as ReadAloudHandler — ElevenLabs' 409 "already_running" and
    // 429 both self-resolve on a short retry.
    private static readonly HttpStatusCode[] TransientStatuses = [HttpStatusCode.Conflict, HttpStatusCode.TooManyRequests];
    private const int MaxAttempts = 3;

    public async Task<Result<SpeakVoiceDto>> Handle(SpeakVoiceCommand cmd, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(cmd.Text))
            return Result<SpeakVoiceDto>.Failure("Text is required.");

        // Sarah (hr) gets her own dedicated voice, separate from Lessons/ReadAloud's VoiceHr —
        // they used to be two independent voices (interview room via the old client-side
        // VITE_ELEVENLABS_VOICE_HR, Read Aloud via this same ElevenLabs:VoiceHr setting), and
        // sharing one here silently swapped Sarah's voice for Read Aloud's when this endpoint
        // was first built. VoiceInterviewHr falls back to the shared one only if it's ever
        // unset, so this can never regress to a hard failure.
        //
        // No ElevenLabs__VoiceMike configured yet — falls back to the technical (James) voice,
        // matching exactly what the old client-side code did (`VOICE_MIKE || VOICE_TECH`).
        var voiceId = cmd.Role switch
        {
            "hr"   => config["ElevenLabs:VoiceInterviewHr"] ?? config["ElevenLabs:VoiceHr"],
            "mike" => config["ElevenLabs:VoiceMike"] ?? config["ElevenLabs:VoiceTech"],
            _      => config["ElevenLabs:VoiceTech"], // "technical" and anything else
        };
        var apiKey = config["ElevenLabs:ApiKey"];
        if (string.IsNullOrWhiteSpace(apiKey) || string.IsNullOrWhiteSpace(voiceId))
            return Result<SpeakVoiceDto>.Failure("Interview voice isn't configured.", 500);

        var key = TtsCacheService.KeyFor(voiceId, cmd.Text);
        var cached = await cache.GetReadUrlIfCachedAsync(key);
        if (cached is not null)
            return Result<SpeakVoiceDto>.Success(new SpeakVoiceDto(cached));

        var client = httpFactory.CreateClient();

        for (var attempt = 1; ; attempt++)
        {
            using var msg = new HttpRequestMessage(HttpMethod.Post, $"https://api.elevenlabs.io/v1/text-to-speech/{voiceId}");
            msg.Headers.Add("xi-api-key", apiKey);
            msg.Content = JsonContent.Create(new
            {
                text = cmd.Text,
                model_id = Model,
                voice_settings = new { stability = 0.5, similarity_boost = 0.75 },
            });

            using var resp = await client.SendAsync(msg, ct);
            if (!resp.IsSuccessStatusCode)
            {
                if (TransientStatuses.Contains(resp.StatusCode) && attempt < MaxAttempts)
                {
                    logger.LogWarning("ElevenLabs returned {Status} for a {Length}-char interview line (attempt {Attempt}/{Max}) — retrying",
                        resp.StatusCode, cmd.Text.Length, attempt, MaxAttempts);
                    await Task.Delay(TimeSpan.FromMilliseconds(500 * attempt), ct);
                    continue;
                }

                var errorBody = await resp.Content.ReadAsStringAsync(ct);
                logger.LogError("ElevenLabs returned {Status} for a {Length}-char interview line (voiceId={VoiceId}): {Body}",
                    resp.StatusCode, cmd.Text.Length, voiceId, errorBody);
                return Result<SpeakVoiceDto>.Failure("Voice generation failed.", 502);
            }

            await using var responseStream = await resp.Content.ReadAsStreamAsync(ct);
            using var buffer = new MemoryStream();
            await responseStream.CopyToAsync(buffer, ct);
            buffer.Position = 0;

            var url = await cache.UploadAndGetReadUrlAsync(key, buffer, "audio/mpeg");
            return Result<SpeakVoiceDto>.Success(new SpeakVoiceDto(url));
        }
    }
}
