/**
 * Career Seed Script
 * Generates ~4,000 career documents via GPT-4o-mini and upserts into
 * Cosmos DB: percentileone-cosmos → interviewme → careers
 *
 * Run: node scripts/seed-careers.mjs
 * Resume: node scripts/seed-careers.mjs --resume
 */

import { CosmosClient } from '@azure/cosmos';
import fs from 'fs';

const COSMOS_CONNECTION = process.env.COSMOS_CONNECTION_STRING;
const OPENAI_API_KEY   = process.env.OPENAI_API_KEY;

if (!COSMOS_CONNECTION || !OPENAI_API_KEY) {
  console.error('Set COSMOS_CONNECTION_STRING and OPENAI_API_KEY env vars before running.');
  process.exit(1);
}
const DB_NAME          = 'interviewme';
const CONTAINER_NAME   = 'careers';
const BATCH_SIZE       = 5;
const DELAY_MS         = 1400;
const PROGRESS_FILE    = 'scripts/seed-progress.json';

const RESUME = process.argv.includes('--resume');

// ── Master career list ─────────────────────────────────────────────────────────
// ~1,600 titles covering UK + USA, from executive roles to trades and everyday jobs.
// GPT-4o-mini generates all salary, workforce, demand, and pathway data.

const CAREERS = [

  // ── TECHNOLOGY ────────────────────────────────────────────────────────────────
  { title: 'Software Engineer',                 category: 'Technology', subcategory: 'Software Development' },
  { title: 'Frontend Developer',                category: 'Technology', subcategory: 'Software Development' },
  { title: 'Backend Developer',                 category: 'Technology', subcategory: 'Software Development' },
  { title: 'Full Stack Developer',              category: 'Technology', subcategory: 'Software Development' },
  { title: 'Mobile App Developer',              category: 'Technology', subcategory: 'Software Development' },
  { title: 'iOS Developer',                     category: 'Technology', subcategory: 'Software Development' },
  { title: 'Android Developer',                 category: 'Technology', subcategory: 'Software Development' },
  { title: 'React Developer',                   category: 'Technology', subcategory: 'Software Development' },
  { title: 'Angular Developer',                 category: 'Technology', subcategory: 'Software Development' },
  { title: 'Vue.js Developer',                  category: 'Technology', subcategory: 'Software Development' },
  { title: '.NET Developer',                    category: 'Technology', subcategory: 'Software Development' },
  { title: 'Java Developer',                    category: 'Technology', subcategory: 'Software Development' },
  { title: 'Python Developer',                  category: 'Technology', subcategory: 'Software Development' },
  { title: 'Golang Developer',                  category: 'Technology', subcategory: 'Software Development' },
  { title: 'Rust Developer',                    category: 'Technology', subcategory: 'Software Development' },
  { title: 'PHP Developer',                     category: 'Technology', subcategory: 'Software Development' },
  { title: 'Ruby on Rails Developer',           category: 'Technology', subcategory: 'Software Development' },
  { title: 'WordPress Developer',               category: 'Technology', subcategory: 'Software Development' },
  { title: 'Shopify Developer',                 category: 'Technology', subcategory: 'Software Development' },
  { title: 'API Developer',                     category: 'Technology', subcategory: 'Software Development' },
  { title: 'Embedded Systems Engineer',         category: 'Technology', subcategory: 'Software Development' },
  { title: 'Firmware Engineer',                 category: 'Technology', subcategory: 'Software Development' },
  { title: 'Game Developer',                    category: 'Technology', subcategory: 'Software Development' },
  { title: 'DevOps Engineer',                   category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Site Reliability Engineer',         category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Cloud Architect',                   category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Cloud Engineer',                    category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Platform Engineer',                 category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Systems Administrator',             category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Linux Administrator',               category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Network Engineer',                  category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Network Administrator',             category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Infrastructure Engineer',           category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Kubernetes Engineer',               category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Azure Engineer',                    category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'AWS Engineer',                      category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'GCP Engineer',                      category: 'Technology', subcategory: 'Infrastructure & DevOps' },
  { title: 'Data Engineer',                     category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Data Analyst',                      category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Data Scientist',                    category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Business Intelligence Analyst',     category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Analytics Engineer',                category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Data Architect',                    category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Data Warehouse Engineer',           category: 'Technology', subcategory: 'Data & Analytics' },
  { title: 'Machine Learning Engineer',         category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'AI Research Scientist',             category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'AI Engineer',                       category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'NLP Engineer',                      category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'Computer Vision Engineer',          category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'Prompt Engineer',                   category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'Generative AI Specialist',          category: 'Technology', subcategory: 'Artificial Intelligence' },
  { title: 'Cybersecurity Analyst',             category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Penetration Tester',                category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Security Engineer',                 category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Information Security Manager',      category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'SOC Analyst',                       category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Ethical Hacker',                    category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Cloud Security Engineer',           category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'IT Auditor',                        category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Identity and Access Manager',       category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'Digital Forensics Analyst',         category: 'Technology', subcategory: 'Cybersecurity' },
  { title: 'QA Engineer',                       category: 'Technology', subcategory: 'Quality Assurance' },
  { title: 'Test Automation Engineer',          category: 'Technology', subcategory: 'Quality Assurance' },
  { title: 'Software Tester',                   category: 'Technology', subcategory: 'Quality Assurance' },
  { title: 'Performance Test Engineer',         category: 'Technology', subcategory: 'Quality Assurance' },
  { title: 'Product Manager',                   category: 'Technology', subcategory: 'Product & Strategy' },
  { title: 'Technical Product Manager',         category: 'Technology', subcategory: 'Product & Strategy' },
  { title: 'Scrum Master',                      category: 'Technology', subcategory: 'Product & Strategy' },
  { title: 'Agile Coach',                       category: 'Technology', subcategory: 'Product & Strategy' },
  { title: 'IT Project Manager',                category: 'Technology', subcategory: 'Product & Strategy' },
  { title: 'Solutions Architect',               category: 'Technology', subcategory: 'Architecture' },
  { title: 'Enterprise Architect',              category: 'Technology', subcategory: 'Architecture' },
  { title: 'Technical Architect',               category: 'Technology', subcategory: 'Architecture' },
  { title: 'Database Administrator',            category: 'Technology', subcategory: 'Databases' },
  { title: 'Database Developer',                category: 'Technology', subcategory: 'Databases' },
  { title: 'IT Support Technician',             category: 'Technology', subcategory: 'IT Support' },
  { title: 'Help Desk Analyst',                 category: 'Technology', subcategory: 'IT Support' },
  { title: 'Service Desk Engineer',             category: 'Technology', subcategory: 'IT Support' },
  { title: 'Technical Support Engineer',        category: 'Technology', subcategory: 'IT Support' },
  { title: 'IT Manager',                        category: 'Technology', subcategory: 'IT Management' },
  { title: 'Chief Technology Officer',          category: 'Technology', subcategory: 'IT Management' },
  { title: 'Chief Information Officer',         category: 'Technology', subcategory: 'IT Management' },
  { title: 'Chief Data Officer',                category: 'Technology', subcategory: 'IT Management' },
  { title: 'Blockchain Developer',              category: 'Technology', subcategory: 'Emerging Tech' },
  { title: 'AR/VR Developer',                   category: 'Technology', subcategory: 'Emerging Tech' },
  { title: 'Robotics Software Engineer',        category: 'Technology', subcategory: 'Emerging Tech' },
  { title: 'Quantum Computing Researcher',      category: 'Technology', subcategory: 'Emerging Tech' },
  { title: 'IoT Engineer',                      category: 'Technology', subcategory: 'Emerging Tech' },
  { title: 'UX Designer',                       category: 'Technology', subcategory: 'Design & UX' },
  { title: 'UI Designer',                       category: 'Technology', subcategory: 'Design & UX' },
  { title: 'UX Researcher',                     category: 'Technology', subcategory: 'Design & UX' },
  { title: 'Product Designer',                  category: 'Technology', subcategory: 'Design & UX' },
  { title: 'SAP Consultant',                    category: 'Technology', subcategory: 'Enterprise Software' },
  { title: 'Salesforce Developer',              category: 'Technology', subcategory: 'Enterprise Software' },
  { title: 'Microsoft Dynamics Consultant',     category: 'Technology', subcategory: 'Enterprise Software' },
  { title: 'ERP Consultant',                    category: 'Technology', subcategory: 'Enterprise Software' },

  // ── HEALTHCARE & MEDICINE ─────────────────────────────────────────────────────
  { title: 'General Practitioner',              category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Hospital Consultant',               category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Surgeon',                           category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Cardiologist',                      category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Neurologist',                       category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Oncologist',                        category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Psychiatrist',                      category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Paediatrician',                     category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Radiologist',                       category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Anaesthetist',                      category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Emergency Medicine Physician',      category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Renal Consultant',                  category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Dermatologist',                     category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Gastroenterologist',                category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Orthopaedic Surgeon',               category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Ophthalmologist',                   category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'ENT Specialist',                    category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Rheumatologist',                    category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Endocrinologist',                   category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Pulmonologist',                     category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Haematologist',                     category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Pathologist',                       category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Geriatrician',                      category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Neonatologist',                     category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Palliative Care Physician',         category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Sports Medicine Doctor',            category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Sexual Health Doctor',              category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Genitourinary Consultant',          category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Infectious Disease Specialist',     category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Immunologist',                      category: 'Healthcare', subcategory: 'Medicine' },
  { title: 'Registered Nurse',                  category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Dialysis Nurse',                    category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Theatre Nurse',                     category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Critical Care Nurse',               category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Community Nurse',                   category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'District Nurse',                    category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Paediatric Nurse',                  category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Mental Health Nurse',               category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Midwife',                           category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Health Visitor',                    category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Nurse Practitioner',                category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Advanced Nurse Practitioner',       category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Oncology Nurse',                    category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Neonatal Nurse',                    category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'District Midwife',                  category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'School Nurse',                      category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Occupational Health Nurse',         category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Healthcare Assistant',              category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Clinical Support Worker',           category: 'Healthcare', subcategory: 'Nursing' },
  { title: 'Pharmacist',                        category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Pharmacy Technician',               category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Physiotherapist',                   category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Occupational Therapist',            category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Speech and Language Therapist',     category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Radiographer',                      category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Dietitian',                         category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Paramedic',                         category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Optometrist',                       category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Audiologist',                       category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Podiatrist',                        category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Prosthetist',                       category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Orthoptist',                        category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Phlebotomist',                      category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Operating Department Practitioner', category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Ambulance Technician',              category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Sonographer',                       category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Orthotist',                         category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Clinical Psychologist',             category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Counselling Psychologist',          category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Psychotherapist',                   category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Counsellor',                        category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Art Therapist',                     category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Music Therapist',                   category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Drama Therapist',                   category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Dance Movement Therapist',          category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Addiction Counsellor',              category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'NHS 111 Health Adviser',            category: 'Healthcare', subcategory: 'Mental Health' },
  { title: 'Dental Surgeon',                    category: 'Healthcare', subcategory: 'Dentistry' },
  { title: 'Dental Hygienist',                  category: 'Healthcare', subcategory: 'Dentistry' },
  { title: 'Orthodontist',                      category: 'Healthcare', subcategory: 'Dentistry' },
  { title: 'Dental Nurse',                      category: 'Healthcare', subcategory: 'Dentistry' },
  { title: 'Dental Therapist',                  category: 'Healthcare', subcategory: 'Dentistry' },
  { title: 'Dental Receptionist',               category: 'Healthcare', subcategory: 'Dentistry' },
  { title: 'Biomedical Scientist',              category: 'Healthcare', subcategory: 'Medical Science' },
  { title: 'Clinical Trials Manager',           category: 'Healthcare', subcategory: 'Medical Science' },
  { title: 'Epidemiologist',                    category: 'Healthcare', subcategory: 'Medical Science' },
  { title: 'Genetic Counsellor',                category: 'Healthcare', subcategory: 'Medical Science' },
  { title: 'Public Health Specialist',          category: 'Healthcare', subcategory: 'Public Health' },
  { title: 'Health Promotion Officer',          category: 'Healthcare', subcategory: 'Public Health' },
  { title: 'Healthcare Manager',                category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'Hospital Administrator',            category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'Care Home Manager',                 category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'GP Practice Manager',               category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'Clinical Coder',                    category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'Medical Secretary',                 category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'Hospital Porter',                   category: 'Healthcare', subcategory: 'Healthcare Management' },
  { title: 'Mortuary Technician',               category: 'Healthcare', subcategory: 'Medical Science' },
  { title: 'Sterile Services Technician',       category: 'Healthcare', subcategory: 'Medical Science' },
  { title: 'Osteopath',                         category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Chiropractor',                      category: 'Healthcare', subcategory: 'Allied Health' },
  { title: 'Sexual Health Adviser',             category: 'Healthcare', subcategory: 'Public Health' },
  { title: 'Prison Healthcare Officer',         category: 'Healthcare', subcategory: 'Nursing' },

  // ── ENGINEERING ───────────────────────────────────────────────────────────────
  { title: 'Mechanical Engineer',               category: 'Engineering', subcategory: 'Mechanical' },
  { title: 'Electrical Engineer',               category: 'Engineering', subcategory: 'Electrical' },
  { title: 'Electronics Engineer',              category: 'Engineering', subcategory: 'Electrical' },
  { title: 'Power Systems Engineer',            category: 'Engineering', subcategory: 'Electrical' },
  { title: 'Civil Engineer',                    category: 'Engineering', subcategory: 'Civil' },
  { title: 'Structural Engineer',               category: 'Engineering', subcategory: 'Civil' },
  { title: 'Geotechnical Engineer',             category: 'Engineering', subcategory: 'Civil' },
  { title: 'Transport Planner',                 category: 'Engineering', subcategory: 'Civil' },
  { title: 'Traffic Engineer',                  category: 'Engineering', subcategory: 'Civil' },
  { title: 'Drainage Engineer',                 category: 'Engineering', subcategory: 'Civil' },
  { title: 'Bridge Engineer',                   category: 'Engineering', subcategory: 'Civil' },
  { title: 'Tunnel Engineer',                   category: 'Engineering', subcategory: 'Civil' },
  { title: 'Water Engineer',                    category: 'Engineering', subcategory: 'Civil' },
  { title: 'Flood Risk Consultant',             category: 'Engineering', subcategory: 'Environmental' },
  { title: 'Chemical Engineer',                 category: 'Engineering', subcategory: 'Chemical' },
  { title: 'Process Engineer',                  category: 'Engineering', subcategory: 'Chemical' },
  { title: 'Aerospace Engineer',                category: 'Engineering', subcategory: 'Aerospace' },
  { title: 'Avionics Engineer',                 category: 'Engineering', subcategory: 'Aerospace' },
  { title: 'Automotive Engineer',               category: 'Engineering', subcategory: 'Automotive' },
  { title: 'EV Engineer',                       category: 'Engineering', subcategory: 'Automotive' },
  { title: 'Manufacturing Engineer',            category: 'Engineering', subcategory: 'Manufacturing' },
  { title: 'Production Engineer',               category: 'Engineering', subcategory: 'Manufacturing' },
  { title: 'Quality Engineer',                  category: 'Engineering', subcategory: 'Manufacturing' },
  { title: 'Environmental Engineer',            category: 'Engineering', subcategory: 'Environmental' },
  { title: 'Energy Engineer',                   category: 'Engineering', subcategory: 'Energy' },
  { title: 'Renewable Energy Engineer',         category: 'Engineering', subcategory: 'Energy' },
  { title: 'Wind Turbine Engineer',             category: 'Engineering', subcategory: 'Energy' },
  { title: 'Solar Energy Engineer',             category: 'Engineering', subcategory: 'Energy' },
  { title: 'Nuclear Engineer',                  category: 'Engineering', subcategory: 'Energy' },
  { title: 'Petroleum Engineer',                category: 'Engineering', subcategory: 'Energy' },
  { title: 'Biomedical Engineer',               category: 'Engineering', subcategory: 'Biomedical' },
  { title: 'Marine Engineer',                   category: 'Engineering', subcategory: 'Marine' },
  { title: 'Naval Architect',                   category: 'Engineering', subcategory: 'Marine' },
  { title: 'Telecommunications Engineer',       category: 'Engineering', subcategory: 'Telecoms' },
  { title: 'RF Engineer',                       category: 'Engineering', subcategory: 'Telecoms' },
  { title: 'Control Systems Engineer',          category: 'Engineering', subcategory: 'Control & Automation' },
  { title: 'Robotics Engineer',                 category: 'Engineering', subcategory: 'Control & Automation' },
  { title: 'Instrumentation Engineer',          category: 'Engineering', subcategory: 'Control & Automation' },
  { title: 'Automation Engineer',               category: 'Engineering', subcategory: 'Control & Automation' },
  { title: 'Maintenance Engineer',              category: 'Engineering', subcategory: 'Maintenance' },
  { title: 'Reliability Engineer',              category: 'Engineering', subcategory: 'Maintenance' },
  { title: 'Fire Engineer',                     category: 'Engineering', subcategory: 'Safety' },
  { title: 'Health and Safety Engineer',        category: 'Engineering', subcategory: 'Safety' },
  { title: 'Project Engineer',                  category: 'Engineering', subcategory: 'Project Management' },
  { title: 'Principal Engineer',                category: 'Engineering', subcategory: 'Senior' },
  { title: 'Chief Engineer',                    category: 'Engineering', subcategory: 'Senior' },
  { title: 'Acoustic Consultant',               category: 'Engineering', subcategory: 'Specialist Engineering' },
  { title: 'Corrosion Engineer',                category: 'Engineering', subcategory: 'Specialist Engineering' },
  { title: 'Hydraulic Engineer',                category: 'Engineering', subcategory: 'Specialist Engineering' },
  { title: 'Materials Engineer',                category: 'Engineering', subcategory: 'Specialist Engineering' },

  // ── FINANCE & ACCOUNTING ──────────────────────────────────────────────────────
  { title: 'Accountant',                        category: 'Finance', subcategory: 'Accounting' },
  { title: 'Management Accountant',             category: 'Finance', subcategory: 'Accounting' },
  { title: 'Financial Accountant',              category: 'Finance', subcategory: 'Accounting' },
  { title: 'Chartered Accountant',              category: 'Finance', subcategory: 'Accounting' },
  { title: 'Auditor',                           category: 'Finance', subcategory: 'Accounting' },
  { title: 'Tax Adviser',                       category: 'Finance', subcategory: 'Accounting' },
  { title: 'Forensic Accountant',               category: 'Finance', subcategory: 'Accounting' },
  { title: 'Bookkeeper',                        category: 'Finance', subcategory: 'Accounting' },
  { title: 'Payroll Manager',                   category: 'Finance', subcategory: 'Accounting' },
  { title: 'Accounts Assistant',                category: 'Finance', subcategory: 'Accounting' },
  { title: 'Accounts Payable Clerk',            category: 'Finance', subcategory: 'Accounting' },
  { title: 'Accounts Receivable Clerk',         category: 'Finance', subcategory: 'Accounting' },
  { title: 'Credit Controller',                 category: 'Finance', subcategory: 'Accounting' },
  { title: 'Financial Controller',              category: 'Finance', subcategory: 'Accounting' },
  { title: 'Investment Banker',                 category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Financial Analyst',                 category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Equity Analyst',                    category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Portfolio Manager',                 category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Hedge Fund Manager',                category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Trader',                            category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Quantitative Analyst',              category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Stockbroker',                       category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Foreign Exchange Trader',           category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Derivatives Analyst',               category: 'Finance', subcategory: 'Banking & Investment' },
  { title: 'Risk Analyst',                      category: 'Finance', subcategory: 'Risk & Compliance' },
  { title: 'Compliance Officer',                category: 'Finance', subcategory: 'Risk & Compliance' },
  { title: 'Credit Analyst',                    category: 'Finance', subcategory: 'Risk & Compliance' },
  { title: 'AML Analyst',                       category: 'Finance', subcategory: 'Risk & Compliance' },
  { title: 'KYC Analyst',                       category: 'Finance', subcategory: 'Risk & Compliance' },
  { title: 'Fraud Analyst',                     category: 'Finance', subcategory: 'Risk & Compliance' },
  { title: 'Actuarial Analyst',                 category: 'Finance', subcategory: 'Actuarial & Insurance' },
  { title: 'Actuary',                           category: 'Finance', subcategory: 'Actuarial & Insurance' },
  { title: 'Insurance Underwriter',             category: 'Finance', subcategory: 'Actuarial & Insurance' },
  { title: 'Claims Handler',                    category: 'Finance', subcategory: 'Actuarial & Insurance' },
  { title: 'Insurance Broker',                  category: 'Finance', subcategory: 'Actuarial & Insurance' },
  { title: 'Loss Adjuster',                     category: 'Finance', subcategory: 'Actuarial & Insurance' },
  { title: 'Financial Planner',                 category: 'Finance', subcategory: 'Financial Advisory' },
  { title: 'Independent Financial Adviser',     category: 'Finance', subcategory: 'Financial Advisory' },
  { title: 'Mortgage Adviser',                  category: 'Finance', subcategory: 'Financial Advisory' },
  { title: 'Mortgage Broker',                   category: 'Finance', subcategory: 'Financial Advisory' },
  { title: 'Wealth Manager',                    category: 'Finance', subcategory: 'Financial Advisory' },
  { title: 'Debt Adviser',                      category: 'Finance', subcategory: 'Financial Advisory' },
  { title: 'Chief Financial Officer',           category: 'Finance', subcategory: 'Senior Finance' },
  { title: 'Finance Director',                  category: 'Finance', subcategory: 'Senior Finance' },
  { title: 'Treasury Manager',                  category: 'Finance', subcategory: 'Senior Finance' },

  // ── LEGAL ─────────────────────────────────────────────────────────────────────
  { title: 'Solicitor',                         category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Barrister',                         category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Legal Executive',                   category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Paralegal',                         category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Corporate Lawyer',                  category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Criminal Lawyer',                   category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Family Lawyer',                     category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Employment Lawyer',                 category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Immigration Lawyer',                category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Intellectual Property Lawyer',      category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Conveyancer',                       category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Tax Lawyer',                        category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Human Rights Lawyer',               category: 'Legal', subcategory: 'Legal Practice' },
  { title: 'Judge',                             category: 'Legal', subcategory: 'Judiciary' },
  { title: 'Magistrate',                        category: 'Legal', subcategory: 'Judiciary' },
  { title: 'Court Clerk',                       category: 'Legal', subcategory: 'Judiciary' },
  { title: 'Legal Compliance Manager',          category: 'Legal', subcategory: 'Compliance' },
  { title: 'Data Protection Officer',           category: 'Legal', subcategory: 'Compliance' },
  { title: 'Legal Secretary',                   category: 'Legal', subcategory: 'Legal Practice' },

  // ── EDUCATION ─────────────────────────────────────────────────────────────────
  { title: 'Primary School Teacher',            category: 'Education', subcategory: 'Teaching' },
  { title: 'Secondary School Teacher',          category: 'Education', subcategory: 'Teaching' },
  { title: 'Special Educational Needs Teacher', category: 'Education', subcategory: 'Teaching' },
  { title: 'Early Years Practitioner',          category: 'Education', subcategory: 'Teaching' },
  { title: 'Further Education Lecturer',        category: 'Education', subcategory: 'Teaching' },
  { title: 'ESOL Teacher',                      category: 'Education', subcategory: 'Teaching' },
  { title: 'Art Teacher',                       category: 'Education', subcategory: 'Teaching' },
  { title: 'Music Teacher',                     category: 'Education', subcategory: 'Teaching' },
  { title: 'Drama Teacher',                     category: 'Education', subcategory: 'Teaching' },
  { title: 'PE Teacher',                        category: 'Education', subcategory: 'Teaching' },
  { title: 'Mathematics Teacher',               category: 'Education', subcategory: 'Teaching' },
  { title: 'Science Teacher',                   category: 'Education', subcategory: 'Teaching' },
  { title: 'English Teacher',                   category: 'Education', subcategory: 'Teaching' },
  { title: 'University Lecturer',               category: 'Education', subcategory: 'Higher Education' },
  { title: 'Professor',                         category: 'Education', subcategory: 'Higher Education' },
  { title: 'Research Fellow',                   category: 'Education', subcategory: 'Higher Education' },
  { title: 'Academic Librarian',                category: 'Education', subcategory: 'Higher Education' },
  { title: 'Teaching Assistant',                category: 'Education', subcategory: 'Support Roles' },
  { title: 'Learning Support Assistant',        category: 'Education', subcategory: 'Support Roles' },
  { title: 'SENCO',                             category: 'Education', subcategory: 'Support Roles' },
  { title: 'Educational Psychologist',          category: 'Education', subcategory: 'Support Roles' },
  { title: 'School Counsellor',                 category: 'Education', subcategory: 'Support Roles' },
  { title: 'School Business Manager',           category: 'Education', subcategory: 'Support Roles' },
  { title: 'Headteacher',                       category: 'Education', subcategory: 'Leadership' },
  { title: 'Deputy Headteacher',                category: 'Education', subcategory: 'Leadership' },
  { title: 'Academy Principal',                 category: 'Education', subcategory: 'Leadership' },
  { title: 'Training Manager',                  category: 'Education', subcategory: 'Corporate Training' },
  { title: 'L&D Specialist',                    category: 'Education', subcategory: 'Corporate Training' },
  { title: 'Instructional Designer',            category: 'Education', subcategory: 'Corporate Training' },
  { title: 'Corporate Trainer',                 category: 'Education', subcategory: 'Corporate Training' },
  { title: 'Private Tutor',                     category: 'Education', subcategory: 'Tutoring' },
  { title: 'Online Tutor',                      category: 'Education', subcategory: 'Tutoring' },
  { title: 'Nursery Nurse',                     category: 'Education', subcategory: 'Early Years' },
  { title: 'Childminder',                       category: 'Education', subcategory: 'Early Years' },
  { title: 'Nanny',                             category: 'Education', subcategory: 'Early Years' },
  { title: 'Playworker',                        category: 'Education', subcategory: 'Early Years' },
  { title: 'Librarian',                         category: 'Education', subcategory: 'Library & Information' },
  { title: 'Library Assistant',                 category: 'Education', subcategory: 'Library & Information' },
  { title: 'Archivist',                         category: 'Education', subcategory: 'Library & Information' },

  // ── CONSTRUCTION & TRADES ─────────────────────────────────────────────────────
  { title: 'Architect',                         category: 'Construction', subcategory: 'Architecture & Design' },
  { title: 'Landscape Architect',               category: 'Construction', subcategory: 'Architecture & Design' },
  { title: 'Interior Designer',                 category: 'Construction', subcategory: 'Architecture & Design' },
  { title: 'Urban Planner',                     category: 'Construction', subcategory: 'Architecture & Design' },
  { title: 'Building Surveyor',                 category: 'Construction', subcategory: 'Surveying' },
  { title: 'Quantity Surveyor',                 category: 'Construction', subcategory: 'Surveying' },
  { title: 'Land Surveyor',                     category: 'Construction', subcategory: 'Surveying' },
  { title: 'Valuation Surveyor',                category: 'Construction', subcategory: 'Surveying' },
  { title: 'Construction Project Manager',      category: 'Construction', subcategory: 'Project Management' },
  { title: 'Site Manager',                      category: 'Construction', subcategory: 'Project Management' },
  { title: 'Contracts Manager',                 category: 'Construction', subcategory: 'Project Management' },
  { title: 'Bricklayer',                        category: 'Construction', subcategory: 'Trades' },
  { title: 'Carpenter',                         category: 'Construction', subcategory: 'Trades' },
  { title: 'Joiner',                            category: 'Construction', subcategory: 'Trades' },
  { title: 'Cabinet Maker',                     category: 'Construction', subcategory: 'Trades' },
  { title: 'Electrician',                       category: 'Construction', subcategory: 'Trades' },
  { title: 'Plumber',                           category: 'Construction', subcategory: 'Trades' },
  { title: 'Gas Engineer',                      category: 'Construction', subcategory: 'Trades' },
  { title: 'Painter and Decorator',             category: 'Construction', subcategory: 'Trades' },
  { title: 'Plasterer',                         category: 'Construction', subcategory: 'Trades' },
  { title: 'Roofer',                            category: 'Construction', subcategory: 'Trades' },
  { title: 'Glazier',                           category: 'Construction', subcategory: 'Trades' },
  { title: 'Floor Layer',                       category: 'Construction', subcategory: 'Trades' },
  { title: 'Tiler',                             category: 'Construction', subcategory: 'Trades' },
  { title: 'Scaffolder',                        category: 'Construction', subcategory: 'Trades' },
  { title: 'Steel Erector',                     category: 'Construction', subcategory: 'Trades' },
  { title: 'Plant Operator',                    category: 'Construction', subcategory: 'Trades' },
  { title: 'Crane Operator',                    category: 'Construction', subcategory: 'Trades' },
  { title: 'Demolition Worker',                 category: 'Construction', subcategory: 'Trades' },
  { title: 'Insulation Fitter',                 category: 'Construction', subcategory: 'Trades' },
  { title: 'Dryliner',                          category: 'Construction', subcategory: 'Trades' },
  { title: 'Pipelayer',                         category: 'Construction', subcategory: 'Trades' },
  { title: 'Groundworker',                      category: 'Construction', subcategory: 'Trades' },
  { title: 'Estimator',                         category: 'Construction', subcategory: 'Commercial' },
  { title: 'Procurement Manager',               category: 'Construction', subcategory: 'Commercial' },
  { title: 'BIM Manager',                       category: 'Construction', subcategory: 'Technology' },
  { title: 'CAD Technician',                    category: 'Construction', subcategory: 'Technology' },
  { title: 'Heating Engineer',                  category: 'Construction', subcategory: 'Mechanical & HVAC' },
  { title: 'HVAC Engineer',                     category: 'Construction', subcategory: 'Mechanical & HVAC' },
  { title: 'Refrigeration Engineer',            category: 'Construction', subcategory: 'Mechanical & HVAC' },
  { title: 'Solar Panel Installer',             category: 'Construction', subcategory: 'Green Trades' },
  { title: 'Heat Pump Installer',               category: 'Construction', subcategory: 'Green Trades' },
  { title: 'EV Charger Installer',              category: 'Construction', subcategory: 'Green Trades' },
  { title: 'Locksmith',                         category: 'Construction', subcategory: 'Trades' },
  { title: 'Window Fitter',                     category: 'Construction', subcategory: 'Trades' },

  // ── SCIENCE & RESEARCH ────────────────────────────────────────────────────────
  { title: 'Biologist',                         category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Microbiologist',                    category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Biochemist',                        category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Geneticist',                        category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Ecologist',                         category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Zoologist',                         category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Botanist',                          category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Marine Biologist',                  category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Neuroscientist',                    category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Virologist',                        category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Immunologist (Research)',           category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Toxicologist',                      category: 'Science', subcategory: 'Life Sciences' },
  { title: 'Chemist',                           category: 'Science', subcategory: 'Physical Sciences' },
  { title: 'Analytical Chemist',                category: 'Science', subcategory: 'Physical Sciences' },
  { title: 'Pharmaceutical Chemist',            category: 'Science', subcategory: 'Physical Sciences' },
  { title: 'Physicist',                         category: 'Science', subcategory: 'Physical Sciences' },
  { title: 'Astrophysicist',                    category: 'Science', subcategory: 'Physical Sciences' },
  { title: 'Geologist',                         category: 'Science', subcategory: 'Earth Sciences' },
  { title: 'Geophysicist',                      category: 'Science', subcategory: 'Earth Sciences' },
  { title: 'Meteorologist',                     category: 'Science', subcategory: 'Earth Sciences' },
  { title: 'Oceanographer',                     category: 'Science', subcategory: 'Earth Sciences' },
  { title: 'Environmental Scientist',           category: 'Science', subcategory: 'Environmental Science' },
  { title: 'Climate Scientist',                 category: 'Science', subcategory: 'Environmental Science' },
  { title: 'Air Quality Scientist',             category: 'Science', subcategory: 'Environmental Science' },
  { title: 'Food Scientist',                    category: 'Science', subcategory: 'Applied Sciences' },
  { title: 'Materials Scientist',               category: 'Science', subcategory: 'Applied Sciences' },
  { title: 'Nanotechnologist',                  category: 'Science', subcategory: 'Applied Sciences' },
  { title: 'Research Scientist',                category: 'Science', subcategory: 'Research' },
  { title: 'Laboratory Technician',             category: 'Science', subcategory: 'Research' },
  { title: 'Science Writer',                    category: 'Science', subcategory: 'Research' },
  { title: 'Forensic Scientist',                category: 'Science', subcategory: 'Forensic Science' },
  { title: 'Crime Scene Investigator',          category: 'Science', subcategory: 'Forensic Science' },
  { title: 'Fingerprint Expert',                category: 'Science', subcategory: 'Forensic Science' },
  { title: 'Pharmaceutical Scientist',          category: 'Science', subcategory: 'Pharmaceutical' },
  { title: 'Regulatory Affairs Specialist',     category: 'Science', subcategory: 'Pharmaceutical' },

  // ── BUSINESS & MANAGEMENT ─────────────────────────────────────────────────────
  { title: 'Chief Executive Officer',           category: 'Business', subcategory: 'Executive Leadership' },
  { title: 'Managing Director',                 category: 'Business', subcategory: 'Executive Leadership' },
  { title: 'Operations Director',               category: 'Business', subcategory: 'Executive Leadership' },
  { title: 'General Manager',                   category: 'Business', subcategory: 'Management' },
  { title: 'Operations Manager',                category: 'Business', subcategory: 'Management' },
  { title: 'Business Analyst',                  category: 'Business', subcategory: 'Analysis & Strategy' },
  { title: 'Strategy Consultant',               category: 'Business', subcategory: 'Analysis & Strategy' },
  { title: 'Management Consultant',             category: 'Business', subcategory: 'Analysis & Strategy' },
  { title: 'Change Manager',                    category: 'Business', subcategory: 'Analysis & Strategy' },
  { title: 'HR Manager',                        category: 'Business', subcategory: 'Human Resources' },
  { title: 'HR Business Partner',               category: 'Business', subcategory: 'Human Resources' },
  { title: 'Talent Acquisition Specialist',     category: 'Business', subcategory: 'Human Resources' },
  { title: 'Recruiter',                         category: 'Business', subcategory: 'Human Resources' },
  { title: 'Headhunter',                        category: 'Business', subcategory: 'Human Resources' },
  { title: 'Compensation and Benefits Manager', category: 'Business', subcategory: 'Human Resources' },
  { title: 'HR Adviser',                        category: 'Business', subcategory: 'Human Resources' },
  { title: 'Organisational Development Consultant', category: 'Business', subcategory: 'Human Resources' },
  { title: 'Project Manager',                   category: 'Business', subcategory: 'Project Management' },
  { title: 'Programme Manager',                 category: 'Business', subcategory: 'Project Management' },
  { title: 'PMO Analyst',                       category: 'Business', subcategory: 'Project Management' },
  { title: 'Supply Chain Manager',              category: 'Business', subcategory: 'Supply Chain & Logistics' },
  { title: 'Logistics Manager',                 category: 'Business', subcategory: 'Supply Chain & Logistics' },
  { title: 'Procurement Specialist',            category: 'Business', subcategory: 'Supply Chain & Logistics' },
  { title: 'Entrepreneur',                      category: 'Business', subcategory: 'Entrepreneurship' },
  { title: 'Startup Founder',                   category: 'Business', subcategory: 'Entrepreneurship' },
  { title: 'Business Development Manager',      category: 'Business', subcategory: 'Business Development' },
  { title: 'Executive Assistant',               category: 'Business', subcategory: 'Administration' },
  { title: 'Office Manager',                    category: 'Business', subcategory: 'Administration' },
  { title: 'Personal Assistant',                category: 'Business', subcategory: 'Administration' },
  { title: 'Administrator',                     category: 'Business', subcategory: 'Administration' },
  { title: 'Receptionist',                      category: 'Business', subcategory: 'Administration' },
  { title: 'Data Entry Clerk',                  category: 'Business', subcategory: 'Administration' },

  // ── SALES & MARKETING ─────────────────────────────────────────────────────────
  { title: 'Sales Manager',                     category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Account Manager',                   category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Sales Executive',                   category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Business Development Executive',    category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Field Sales Representative',        category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Key Account Manager',               category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Inside Sales Executive',            category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Sales Director',                    category: 'Sales & Marketing', subcategory: 'Sales' },
  { title: 'Marketing Manager',                 category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Digital Marketing Manager',         category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'SEO Specialist',                    category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'PPC Specialist',                    category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Content Marketing Manager',         category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Social Media Manager',              category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Brand Manager',                     category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Email Marketing Specialist',        category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Growth Hacker',                     category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Market Research Analyst',           category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'Affiliate Marketing Manager',       category: 'Sales & Marketing', subcategory: 'Marketing' },
  { title: 'PR Manager',                        category: 'Sales & Marketing', subcategory: 'PR & Communications' },
  { title: 'Communications Manager',            category: 'Sales & Marketing', subcategory: 'PR & Communications' },
  { title: 'Press Officer',                     category: 'Sales & Marketing', subcategory: 'PR & Communications' },
  { title: 'E-commerce Manager',                category: 'Sales & Marketing', subcategory: 'E-commerce' },
  { title: 'Customer Success Manager',          category: 'Sales & Marketing', subcategory: 'Customer Experience' },
  { title: 'Customer Experience Manager',       category: 'Sales & Marketing', subcategory: 'Customer Experience' },

  // ── CREATIVE & MEDIA ──────────────────────────────────────────────────────────
  { title: 'Graphic Designer',                  category: 'Creative', subcategory: 'Design' },
  { title: 'Art Director',                      category: 'Creative', subcategory: 'Design' },
  { title: 'Creative Director',                 category: 'Creative', subcategory: 'Design' },
  { title: 'Motion Graphics Designer',          category: 'Creative', subcategory: 'Design' },
  { title: 'Illustrator',                       category: 'Creative', subcategory: 'Design' },
  { title: 'Typographer',                       category: 'Creative', subcategory: 'Design' },
  { title: 'Web Designer',                      category: 'Creative', subcategory: 'Design' },
  { title: 'Brand Designer',                    category: 'Creative', subcategory: 'Design' },
  { title: 'Copywriter',                        category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Technical Writer',                  category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Content Writer',                    category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Journalist',                        category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Editor',                            category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Screenwriter',                      category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Author',                            category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Ghostwriter',                       category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Subtitler',                         category: 'Creative', subcategory: 'Writing & Content' },
  { title: 'Photographer',                      category: 'Creative', subcategory: 'Photography & Film' },
  { title: 'Wedding Photographer',              category: 'Creative', subcategory: 'Photography & Film' },
  { title: 'Videographer',                      category: 'Creative', subcategory: 'Photography & Film' },
  { title: 'Film Director',                     category: 'Creative', subcategory: 'Photography & Film' },
  { title: 'Video Editor',                      category: 'Creative', subcategory: 'Photography & Film' },
  { title: 'Cinematographer',                   category: 'Creative', subcategory: 'Photography & Film' },
  { title: 'Animator',                          category: 'Creative', subcategory: 'Animation & Gaming' },
  { title: '3D Artist',                         category: 'Creative', subcategory: 'Animation & Gaming' },
  { title: 'Game Designer',                     category: 'Creative', subcategory: 'Animation & Gaming' },
  { title: 'VFX Artist',                        category: 'Creative', subcategory: 'Animation & Gaming' },
  { title: 'Concept Artist',                    category: 'Creative', subcategory: 'Animation & Gaming' },
  { title: 'Musician',                          category: 'Creative', subcategory: 'Music' },
  { title: 'Music Producer',                    category: 'Creative', subcategory: 'Music' },
  { title: 'Sound Engineer',                    category: 'Creative', subcategory: 'Music' },
  { title: 'Composer',                          category: 'Creative', subcategory: 'Music' },
  { title: 'DJ',                                category: 'Creative', subcategory: 'Music' },
  { title: 'Session Musician',                  category: 'Creative', subcategory: 'Music' },
  { title: 'Podcast Producer',                  category: 'Creative', subcategory: 'Audio & Broadcast' },
  { title: 'Radio Presenter',                   category: 'Creative', subcategory: 'Audio & Broadcast' },
  { title: 'TV Presenter',                      category: 'Creative', subcategory: 'Audio & Broadcast' },
  { title: 'Broadcast Journalist',              category: 'Creative', subcategory: 'Audio & Broadcast' },
  { title: 'Voice Actor',                       category: 'Creative', subcategory: 'Audio & Broadcast' },
  { title: 'Stage Actor',                       category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Screen Actor',                      category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Theatre Director',                  category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Casting Director',                  category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Dancer',                            category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Choreographer',                     category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Stand-Up Comedian',                 category: 'Creative', subcategory: 'Performing Arts' },
  { title: 'Literary Agent',                    category: 'Creative', subcategory: 'Publishing' },
  { title: 'Book Publisher',                    category: 'Creative', subcategory: 'Publishing' },
  { title: 'Magazine Editor',                   category: 'Creative', subcategory: 'Publishing' },
  { title: 'Museum Curator',                    category: 'Creative', subcategory: 'Arts & Culture' },
  { title: 'Gallery Manager',                   category: 'Creative', subcategory: 'Arts & Culture' },
  { title: 'Tattoo Artist',                     category: 'Creative', subcategory: 'Arts & Culture' },
  { title: 'Sculptor',                          category: 'Creative', subcategory: 'Arts & Culture' },
  { title: 'Printmaker',                        category: 'Creative', subcategory: 'Arts & Culture' },
  { title: 'Ceramicist',                        category: 'Creative', subcategory: 'Arts & Culture' },

  // ── SOCIAL CARE & SUPPORT ─────────────────────────────────────────────────────
  { title: 'Social Worker',                     category: 'Social Care', subcategory: 'Social Work' },
  { title: "Children's Social Worker",          category: 'Social Care', subcategory: 'Social Work' },
  { title: 'Adult Social Worker',               category: 'Social Care', subcategory: 'Social Work' },
  { title: 'Probation Officer',                 category: 'Social Care', subcategory: 'Social Work' },
  { title: 'Youth Worker',                      category: 'Social Care', subcategory: 'Community Support' },
  { title: 'Community Development Worker',      category: 'Social Care', subcategory: 'Community Support' },
  { title: 'Housing Officer',                   category: 'Social Care', subcategory: 'Community Support' },
  { title: 'Outreach Worker',                   category: 'Social Care', subcategory: 'Community Support' },
  { title: 'Domestic Violence Advocate',        category: 'Social Care', subcategory: 'Community Support' },
  { title: 'Victim Support Worker',             category: 'Social Care', subcategory: 'Community Support' },
  { title: 'Care Worker',                       category: 'Social Care', subcategory: 'Care' },
  { title: 'Support Worker',                    category: 'Social Care', subcategory: 'Care' },
  { title: 'Learning Disability Support Worker', category: 'Social Care', subcategory: 'Care' },
  { title: 'Foster Carer',                      category: 'Social Care', subcategory: 'Care' },
  { title: 'Drug Rehabilitation Worker',        category: 'Social Care', subcategory: 'Care' },
  { title: 'Charity Manager',                   category: 'Social Care', subcategory: 'Charity & Voluntary' },
  { title: 'Fundraiser',                        category: 'Social Care', subcategory: 'Charity & Voluntary' },
  { title: 'Volunteer Coordinator',             category: 'Social Care', subcategory: 'Charity & Voluntary' },
  { title: 'Food Bank Coordinator',             category: 'Social Care', subcategory: 'Charity & Voluntary' },
  { title: 'Benefits Adviser',                  category: 'Social Care', subcategory: 'Community Support' },

  // ── HOSPITALITY & TOURISM ─────────────────────────────────────────────────────
  { title: 'Hotel Manager',                     category: 'Hospitality', subcategory: 'Hotel & Accommodation' },
  { title: 'Front of House Manager',            category: 'Hospitality', subcategory: 'Hotel & Accommodation' },
  { title: 'Revenue Manager',                   category: 'Hospitality', subcategory: 'Hotel & Accommodation' },
  { title: 'Concierge',                         category: 'Hospitality', subcategory: 'Hotel & Accommodation' },
  { title: 'Guest Relations Manager',           category: 'Hospitality', subcategory: 'Hotel & Accommodation' },
  { title: 'Housekeeping Manager',              category: 'Hospitality', subcategory: 'Hotel & Accommodation' },
  { title: 'Chef',                              category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Head Chef',                         category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Sous Chef',                         category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Pastry Chef',                       category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Restaurant Manager',                category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Sommelier',                         category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Barista',                           category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Baker',                             category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Catering Manager',                  category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Pub Manager',                       category: 'Hospitality', subcategory: 'Food & Beverage' },
  { title: 'Event Manager',                     category: 'Hospitality', subcategory: 'Events' },
  { title: 'Wedding Planner',                   category: 'Hospitality', subcategory: 'Events' },
  { title: 'Conference Manager',                category: 'Hospitality', subcategory: 'Events' },
  { title: 'Travel Agent',                      category: 'Hospitality', subcategory: 'Travel & Tourism' },
  { title: 'Tour Guide',                        category: 'Hospitality', subcategory: 'Travel & Tourism' },
  { title: 'Holiday Rep',                       category: 'Hospitality', subcategory: 'Travel & Tourism' },
  { title: 'Cruise Director',                   category: 'Hospitality', subcategory: 'Travel & Tourism' },
  { title: 'Cabin Crew',                        category: 'Hospitality', subcategory: 'Travel & Tourism' },
  { title: 'Tourist Information Officer',       category: 'Hospitality', subcategory: 'Travel & Tourism' },

  // ── TRANSPORT & LOGISTICS ─────────────────────────────────────────────────────
  { title: 'HGV Driver',                        category: 'Transport', subcategory: 'Driving' },
  { title: 'Bus Driver',                        category: 'Transport', subcategory: 'Driving' },
  { title: 'Taxi Driver',                       category: 'Transport', subcategory: 'Driving' },
  { title: 'Delivery Driver',                   category: 'Transport', subcategory: 'Driving' },
  { title: 'Courier',                           category: 'Transport', subcategory: 'Driving' },
  { title: 'Van Driver',                        category: 'Transport', subcategory: 'Driving' },
  { title: 'Removal Driver',                    category: 'Transport', subcategory: 'Driving' },
  { title: 'Train Driver',                      category: 'Transport', subcategory: 'Rail' },
  { title: 'Rail Engineer',                     category: 'Transport', subcategory: 'Rail' },
  { title: 'Signaller',                         category: 'Transport', subcategory: 'Rail' },
  { title: 'Station Manager',                   category: 'Transport', subcategory: 'Rail' },
  { title: 'Commercial Pilot',                  category: 'Transport', subcategory: 'Aviation' },
  { title: 'Air Traffic Controller',            category: 'Transport', subcategory: 'Aviation' },
  { title: 'Ground Operations Agent',           category: 'Transport', subcategory: 'Aviation' },
  { title: 'Aircraft Maintenance Engineer',     category: 'Transport', subcategory: 'Aviation' },
  { title: 'Merchant Navy Officer',             category: 'Transport', subcategory: 'Maritime' },
  { title: 'Port Operations Manager',           category: 'Transport', subcategory: 'Maritime' },
  { title: 'Logistics Coordinator',             category: 'Transport', subcategory: 'Logistics' },
  { title: 'Warehouse Manager',                 category: 'Transport', subcategory: 'Logistics' },
  { title: 'Freight Forwarder',                 category: 'Transport', subcategory: 'Logistics' },
  { title: 'Customs Officer',                   category: 'Transport', subcategory: 'Logistics' },
  { title: 'Fleet Manager',                     category: 'Transport', subcategory: 'Fleet Management' },
  { title: 'Postman',                           category: 'Transport', subcategory: 'Postal' },
  { title: 'Postal Worker',                     category: 'Transport', subcategory: 'Postal' },
  { title: 'Sorting Office Operative',          category: 'Transport', subcategory: 'Postal' },

  // ── AGRICULTURE, ANIMALS & ENVIRONMENT ───────────────────────────────────────
  { title: 'Farmer',                            category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Agronomist',                        category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Agricultural Engineer',             category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Farm Manager',                      category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Dairy Farmer',                      category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Poultry Farmer',                    category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Arable Farmer',                     category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Pig Farmer',                        category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Fish Farmer',                       category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Hydroponic Farmer',                 category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Urban Farmer',                      category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Beekeeper',                         category: 'Agriculture', subcategory: 'Farming' },
  { title: 'Horticulturalist',                  category: 'Agriculture', subcategory: 'Horticulture' },
  { title: 'Landscape Gardener',                category: 'Agriculture', subcategory: 'Horticulture' },
  { title: 'Groundsperson',                     category: 'Agriculture', subcategory: 'Horticulture' },
  { title: 'Garden Designer',                   category: 'Agriculture', subcategory: 'Horticulture' },
  { title: 'Gardener',                          category: 'Agriculture', subcategory: 'Horticulture' },
  { title: 'Florist',                           category: 'Agriculture', subcategory: 'Horticulture' },
  { title: 'Forester',                          category: 'Agriculture', subcategory: 'Forestry' },
  { title: 'Arborist',                          category: 'Agriculture', subcategory: 'Forestry' },
  { title: 'Countryside Ranger',                category: 'Agriculture', subcategory: 'Conservation' },
  { title: 'Park Ranger',                       category: 'Agriculture', subcategory: 'Conservation' },
  { title: 'Conservation Officer',              category: 'Agriculture', subcategory: 'Conservation' },
  { title: 'Vet',                               category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Veterinary Nurse',                  category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Animal Behaviourist',               category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Zookeeper',                         category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Dog Trainer',                       category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Dog Walker',                        category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Pet Groomer',                       category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Kennel Assistant',                  category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Horse Trainer',                     category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Farrier',                           category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Stable Hand',                       category: 'Agriculture', subcategory: 'Animal Care' },
  { title: 'Fisheries Officer',                 category: 'Agriculture', subcategory: 'Fisheries' },
  { title: 'Environmental Health Officer',      category: 'Agriculture', subcategory: 'Environmental Health' },
  { title: 'Waste Management Officer',          category: 'Agriculture', subcategory: 'Environmental Health' },
  { title: 'Pest Controller',                   category: 'Agriculture', subcategory: 'Environmental Health' },

  // ── EMERGENCY SERVICES & MILITARY ─────────────────────────────────────────────
  { title: 'Police Officer',                    category: 'Emergency Services', subcategory: 'Police' },
  { title: 'Detective',                         category: 'Emergency Services', subcategory: 'Police' },
  { title: 'Police Sergeant',                   category: 'Emergency Services', subcategory: 'Police' },
  { title: 'Police Inspector',                  category: 'Emergency Services', subcategory: 'Police' },
  { title: 'PCSO',                              category: 'Emergency Services', subcategory: 'Police' },
  { title: 'Dog Handler',                       category: 'Emergency Services', subcategory: 'Police' },
  { title: 'Traffic Warden',                    category: 'Emergency Services', subcategory: 'Police' },
  { title: 'Firefighter',                       category: 'Emergency Services', subcategory: 'Fire Service' },
  { title: 'Fire Station Manager',              category: 'Emergency Services', subcategory: 'Fire Service' },
  { title: 'Emergency Medical Dispatcher',      category: 'Emergency Services', subcategory: 'Ambulance' },
  { title: 'Search and Rescue Officer',         category: 'Emergency Services', subcategory: 'Rescue' },
  { title: 'Coastguard Officer',                category: 'Emergency Services', subcategory: 'Rescue' },
  { title: 'Beach Lifeguard',                   category: 'Emergency Services', subcategory: 'Rescue' },
  { title: 'Army Officer',                      category: 'Emergency Services', subcategory: 'Military' },
  { title: 'Navy Officer',                      category: 'Emergency Services', subcategory: 'Military' },
  { title: 'RAF Pilot',                         category: 'Emergency Services', subcategory: 'Military' },
  { title: 'Military Intelligence Analyst',     category: 'Emergency Services', subcategory: 'Military' },
  { title: 'Army Medic',                        category: 'Emergency Services', subcategory: 'Military' },
  { title: 'Prison Officer',                    category: 'Emergency Services', subcategory: 'Corrections' },
  { title: 'Prison Psychologist',               category: 'Emergency Services', subcategory: 'Corrections' },
  { title: 'Border Force Officer',              category: 'Emergency Services', subcategory: 'Border & Immigration' },
  { title: 'Immigration Officer',               category: 'Emergency Services', subcategory: 'Border & Immigration' },
  { title: 'Intelligence Analyst',              category: 'Emergency Services', subcategory: 'Intelligence' },

  // ── SPORT & FITNESS ───────────────────────────────────────────────────────────
  { title: 'Personal Trainer',                  category: 'Sport', subcategory: 'Fitness' },
  { title: 'Fitness Instructor',                category: 'Sport', subcategory: 'Fitness' },
  { title: 'Yoga Teacher',                      category: 'Sport', subcategory: 'Fitness' },
  { title: 'Pilates Instructor',                category: 'Sport', subcategory: 'Fitness' },
  { title: 'Pool Lifeguard',                    category: 'Sport', subcategory: 'Fitness' },
  { title: 'Swimming Teacher',                  category: 'Sport', subcategory: 'Fitness' },
  { title: 'Sports Coach',                      category: 'Sport', subcategory: 'Coaching' },
  { title: 'Football Coach',                    category: 'Sport', subcategory: 'Coaching' },
  { title: 'Rugby Coach',                       category: 'Sport', subcategory: 'Coaching' },
  { title: 'Cricket Coach',                     category: 'Sport', subcategory: 'Coaching' },
  { title: 'Tennis Coach',                      category: 'Sport', subcategory: 'Coaching' },
  { title: 'Golf Instructor',                   category: 'Sport', subcategory: 'Coaching' },
  { title: 'Gymnastics Coach',                  category: 'Sport', subcategory: 'Coaching' },
  { title: 'Boxing Coach',                      category: 'Sport', subcategory: 'Coaching' },
  { title: 'Martial Arts Instructor',           category: 'Sport', subcategory: 'Coaching' },
  { title: 'Ski Instructor',                    category: 'Sport', subcategory: 'Coaching' },
  { title: 'Surf Instructor',                   category: 'Sport', subcategory: 'Coaching' },
  { title: 'Strength and Conditioning Coach',   category: 'Sport', subcategory: 'Coaching' },
  { title: 'Sports Scientist',                  category: 'Sport', subcategory: 'Sports Science' },
  { title: 'Sports Physiotherapist',            category: 'Sport', subcategory: 'Sports Medicine' },
  { title: 'Sports Nutritionist',               category: 'Sport', subcategory: 'Sports Medicine' },
  { title: 'Professional Footballer',           category: 'Sport', subcategory: 'Professional Sports' },
  { title: 'Professional Golfer',               category: 'Sport', subcategory: 'Professional Sports' },
  { title: 'Athlete',                           category: 'Sport', subcategory: 'Professional Sports' },
  { title: 'Jockey',                            category: 'Sport', subcategory: 'Professional Sports' },
  { title: 'Sports Agent',                      category: 'Sport', subcategory: 'Sports Business' },
  { title: 'Sports Analyst',                    category: 'Sport', subcategory: 'Sports Business' },
  { title: 'Leisure Centre Manager',            category: 'Sport', subcategory: 'Leisure Management' },
  { title: 'Equestrian Coach',                  category: 'Sport', subcategory: 'Coaching' },

  // ── PROPERTY & REAL ESTATE ────────────────────────────────────────────────────
  { title: 'Estate Agent',                      category: 'Property', subcategory: 'Sales & Lettings' },
  { title: 'Letting Agent',                     category: 'Property', subcategory: 'Sales & Lettings' },
  { title: 'Property Manager',                  category: 'Property', subcategory: 'Property Management' },
  { title: 'Facilities Manager',                category: 'Property', subcategory: 'Property Management' },
  { title: 'Asset Manager',                     category: 'Property', subcategory: 'Property Investment' },
  { title: 'Property Developer',                category: 'Property', subcategory: 'Property Investment' },
  { title: 'Real Estate Analyst',               category: 'Property', subcategory: 'Property Investment' },
  { title: 'Chartered Surveyor',                category: 'Property', subcategory: 'Surveying' },
  { title: 'Commercial Property Manager',       category: 'Property', subcategory: 'Commercial Property' },
  { title: 'Mortgage Adviser (Property)',       category: 'Property', subcategory: 'Finance' },

  // ── PUBLIC SECTOR & GOVERNMENT ────────────────────────────────────────────────
  { title: 'Civil Servant',                     category: 'Public Sector', subcategory: 'Civil Service' },
  { title: 'Policy Adviser',                    category: 'Public Sector', subcategory: 'Civil Service' },
  { title: 'Local Government Officer',          category: 'Public Sector', subcategory: 'Local Government' },
  { title: 'Town Planner',                      category: 'Public Sector', subcategory: 'Local Government' },
  { title: 'Council Tax Officer',               category: 'Public Sector', subcategory: 'Local Government' },
  { title: 'Diplomat',                          category: 'Public Sector', subcategory: 'Foreign Affairs' },
  { title: 'Tax Inspector',                     category: 'Public Sector', subcategory: 'Revenue & Taxation' },
  { title: 'Trading Standards Officer',         category: 'Public Sector', subcategory: 'Regulation' },
  { title: 'Ofsted Inspector',                  category: 'Public Sector', subcategory: 'Regulation' },
  { title: 'Coroner',                           category: 'Public Sector', subcategory: 'Courts & Justice' },
  { title: 'Court Clerk',                       category: 'Public Sector', subcategory: 'Courts & Justice' },
  { title: 'Registrar',                         category: 'Public Sector', subcategory: 'Courts & Justice' },
  { title: 'Civil Service Fast Streamer',       category: 'Public Sector', subcategory: 'Civil Service' },
  { title: 'Lollipop Person',                   category: 'Public Sector', subcategory: 'Local Government' },
  { title: 'Parking Enforcement Officer',       category: 'Public Sector', subcategory: 'Local Government' },

  // ── RETAIL & CUSTOMER SERVICE ─────────────────────────────────────────────────
  { title: 'Retail Manager',                    category: 'Retail', subcategory: 'Retail Management' },
  { title: 'Store Manager',                     category: 'Retail', subcategory: 'Retail Management' },
  { title: 'Supermarket Manager',               category: 'Retail', subcategory: 'Retail Management' },
  { title: 'Visual Merchandiser',               category: 'Retail', subcategory: 'Merchandising' },
  { title: 'Buyer',                             category: 'Retail', subcategory: 'Buying & Merchandising' },
  { title: 'Fashion Buyer',                     category: 'Retail', subcategory: 'Buying & Merchandising' },
  { title: 'Customer Service Manager',          category: 'Retail', subcategory: 'Customer Service' },
  { title: 'Call Centre Manager',               category: 'Retail', subcategory: 'Customer Service' },
  { title: 'Call Centre Agent',                 category: 'Retail', subcategory: 'Customer Service' },
  { title: 'Checkout Operator',                 category: 'Retail', subcategory: 'Retail' },
  { title: 'Retail Pharmacist',                 category: 'Retail', subcategory: 'Specialist Retail' },
  { title: 'Optician',                          category: 'Retail', subcategory: 'Specialist Retail' },
  { title: 'Jeweller',                          category: 'Retail', subcategory: 'Specialist Retail' },
  { title: 'Antiques Dealer',                   category: 'Retail', subcategory: 'Specialist Retail' },
  { title: 'Auctioneer',                        category: 'Retail', subcategory: 'Specialist Retail' },
  { title: 'Pawnbroker',                        category: 'Retail', subcategory: 'Specialist Retail' },

  // ── BEAUTY & WELLNESS ─────────────────────────────────────────────────────────
  { title: 'Hairdresser',                       category: 'Beauty & Wellness', subcategory: 'Hair' },
  { title: 'Barber',                            category: 'Beauty & Wellness', subcategory: 'Hair' },
  { title: 'Colourist',                         category: 'Beauty & Wellness', subcategory: 'Hair' },
  { title: 'Beautician',                        category: 'Beauty & Wellness', subcategory: 'Beauty' },
  { title: 'Nail Technician',                   category: 'Beauty & Wellness', subcategory: 'Beauty' },
  { title: 'Makeup Artist',                     category: 'Beauty & Wellness', subcategory: 'Beauty' },
  { title: 'Aesthetician',                      category: 'Beauty & Wellness', subcategory: 'Beauty' },
  { title: 'Tattoo Artist (Beauty)',            category: 'Beauty & Wellness', subcategory: 'Beauty' },
  { title: 'Massage Therapist',                 category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Spa Manager',                       category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Nutritionist',                      category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Life Coach',                        category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Reflexologist',                     category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Acupuncturist',                     category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Hypnotherapist',                    category: 'Beauty & Wellness', subcategory: 'Wellness' },
  { title: 'Aromatherapist',                    category: 'Beauty & Wellness', subcategory: 'Wellness' },

  // ── MANUFACTURING & INDUSTRY ──────────────────────────────────────────────────
  { title: 'CNC Machinist',                     category: 'Manufacturing', subcategory: 'CNC & Machining' },
  { title: 'CNC Programmer',                    category: 'Manufacturing', subcategory: 'CNC & Machining' },
  { title: 'Tool and Die Maker',                category: 'Manufacturing', subcategory: 'CNC & Machining' },
  { title: 'Welder',                            category: 'Manufacturing', subcategory: 'Welding & Fabrication' },
  { title: 'Fabricator',                        category: 'Manufacturing', subcategory: 'Welding & Fabrication' },
  { title: 'Sheet Metal Worker',                category: 'Manufacturing', subcategory: 'Welding & Fabrication' },
  { title: 'Pipefitter',                        category: 'Manufacturing', subcategory: 'Welding & Fabrication' },
  { title: 'Fitter',                            category: 'Manufacturing', subcategory: 'Assembly & Fitting' },
  { title: 'Assembly Operative',                category: 'Manufacturing', subcategory: 'Assembly & Fitting' },
  { title: 'Production Operative',              category: 'Manufacturing', subcategory: 'Production' },
  { title: 'Factory Manager',                   category: 'Manufacturing', subcategory: 'Production' },
  { title: 'Quality Control Inspector',         category: 'Manufacturing', subcategory: 'Quality' },
  { title: 'Health and Safety Manager',         category: 'Manufacturing', subcategory: 'Safety' },
  { title: 'Lean Manufacturing Engineer',       category: 'Manufacturing', subcategory: 'Continuous Improvement' },
  { title: 'Six Sigma Black Belt',              category: 'Manufacturing', subcategory: 'Continuous Improvement' },
  { title: 'Textile Technologist',              category: 'Manufacturing', subcategory: 'Textiles' },
  { title: 'Printing Technician',               category: 'Manufacturing', subcategory: 'Print' },
  { title: 'Food Production Operative',         category: 'Manufacturing', subcategory: 'Food Manufacturing' },
  { title: 'Butcher',                           category: 'Manufacturing', subcategory: 'Food Manufacturing' },
  { title: 'Brewer',                            category: 'Manufacturing', subcategory: 'Food Manufacturing' },
  { title: 'Distiller',                         category: 'Manufacturing', subcategory: 'Food Manufacturing' },

  // ── FASHION, TEXTILES & CRAFTS ────────────────────────────────────────────────
  { title: 'Fashion Designer',                  category: 'Fashion', subcategory: 'Design' },
  { title: 'Textile Designer',                  category: 'Fashion', subcategory: 'Design' },
  { title: 'Pattern Cutter',                    category: 'Fashion', subcategory: 'Production' },
  { title: 'Seamstress',                        category: 'Fashion', subcategory: 'Production' },
  { title: 'Tailor',                            category: 'Fashion', subcategory: 'Production' },
  { title: 'Milliner',                          category: 'Fashion', subcategory: 'Production' },
  { title: 'Jewellery Designer',                category: 'Fashion', subcategory: 'Design' },
  { title: 'Silversmith',                       category: 'Fashion', subcategory: 'Craft' },
  { title: 'Goldsmith',                         category: 'Fashion', subcategory: 'Craft' },
  { title: 'Watchmaker',                        category: 'Fashion', subcategory: 'Craft' },
  { title: 'Glassblower',                       category: 'Fashion', subcategory: 'Craft' },
  { title: 'Personal Stylist',                  category: 'Fashion', subcategory: 'Styling' },
  { title: 'Image Consultant',                  category: 'Fashion', subcategory: 'Styling' },
  { title: 'Fashion Photographer',              category: 'Fashion', subcategory: 'Media' },
  { title: 'Costume Designer',                  category: 'Fashion', subcategory: 'Media' },

  // ── LANGUAGE & TRANSLATION ────────────────────────────────────────────────────
  { title: 'Interpreter',                       category: 'Language', subcategory: 'Interpreting' },
  { title: 'Court Interpreter',                 category: 'Language', subcategory: 'Interpreting' },
  { title: 'Conference Interpreter',            category: 'Language', subcategory: 'Interpreting' },
  { title: 'Sign Language Interpreter',         category: 'Language', subcategory: 'Interpreting' },
  { title: 'Translator',                        category: 'Language', subcategory: 'Translation' },
  { title: 'Literary Translator',               category: 'Language', subcategory: 'Translation' },
  { title: 'Medical Translator',                category: 'Language', subcategory: 'Translation' },
  { title: 'Transcriptionist',                  category: 'Language', subcategory: 'Transcription' },
  { title: 'Medical Transcriptionist',          category: 'Language', subcategory: 'Transcription' },
  { title: 'Language Teacher',                  category: 'Language', subcategory: 'Teaching' },

  // ── FUNERAL & MEMORIALISATION ──────────────────────────────────────────────────
  { title: 'Funeral Director',                  category: 'Funeral Services', subcategory: 'Funeral' },
  { title: 'Embalmer',                          category: 'Funeral Services', subcategory: 'Funeral' },
  { title: 'Crematorium Technician',            category: 'Funeral Services', subcategory: 'Funeral' },
  { title: 'Funeral Arranger',                  category: 'Funeral Services', subcategory: 'Funeral' },

  // ── CLEANING & FACILITIES ─────────────────────────────────────────────────────
  { title: 'Cleaning Operative',                category: 'Facilities', subcategory: 'Cleaning' },
  { title: 'Window Cleaner',                    category: 'Facilities', subcategory: 'Cleaning' },
  { title: 'Contract Cleaner',                  category: 'Facilities', subcategory: 'Cleaning' },
  { title: 'Domestic Cleaner',                  category: 'Facilities', subcategory: 'Cleaning' },
  { title: 'Janitor',                           category: 'Facilities', subcategory: 'Cleaning' },
  { title: 'Facilities Coordinator',            category: 'Facilities', subcategory: 'Facilities Management' },
  { title: 'Caretaker',                         category: 'Facilities', subcategory: 'Facilities Management' },
  { title: 'Chimney Sweep',                     category: 'Facilities', subcategory: 'Cleaning' },
  { title: 'Laundry Operative',                 category: 'Facilities', subcategory: 'Cleaning' },

  // ── SECURITY ──────────────────────────────────────────────────────────────────
  { title: 'Security Guard',                    category: 'Security', subcategory: 'Physical Security' },
  { title: 'Door Supervisor',                   category: 'Security', subcategory: 'Physical Security' },
  { title: 'CCTV Operator',                     category: 'Security', subcategory: 'Physical Security' },
  { title: 'Close Protection Officer',          category: 'Security', subcategory: 'Physical Security' },
  { title: 'Security Manager',                  category: 'Security', subcategory: 'Physical Security' },
  { title: 'Loss Prevention Officer',           category: 'Security', subcategory: 'Physical Security' },
  { title: 'Fraud Investigator',                category: 'Security', subcategory: 'Investigation' },
  { title: 'Private Investigator',              category: 'Security', subcategory: 'Investigation' },

  // ── MEDIA & JOURNALISM ────────────────────────────────────────────────────────
  { title: 'News Anchor',                       category: 'Media', subcategory: 'Broadcast' },
  { title: 'Sports Journalist',                 category: 'Media', subcategory: 'Journalism' },
  { title: 'Political Journalist',              category: 'Media', subcategory: 'Journalism' },
  { title: 'Investigative Journalist',          category: 'Media', subcategory: 'Journalism' },
  { title: 'Photo Journalist',                  category: 'Media', subcategory: 'Journalism' },
  { title: 'News Editor',                       category: 'Media', subcategory: 'Journalism' },
  { title: 'Sub-Editor',                        category: 'Media', subcategory: 'Journalism' },
  { title: 'Social Media Journalist',           category: 'Media', subcategory: 'Digital Media' },
  { title: 'Content Creator',                   category: 'Media', subcategory: 'Digital Media' },
  { title: 'YouTuber',                          category: 'Media', subcategory: 'Digital Media' },
  { title: 'TikTok Creator',                    category: 'Media', subcategory: 'Digital Media' },
  { title: 'Influencer',                        category: 'Media', subcategory: 'Digital Media' },
  { title: 'Advertising Creative',              category: 'Media', subcategory: 'Advertising' },
  { title: 'Media Planner',                     category: 'Media', subcategory: 'Advertising' },
  { title: 'Production Manager',                category: 'Media', subcategory: 'Production' },

  // ── PHARMACEUTICAL & BIOTECH ──────────────────────────────────────────────────
  { title: 'Pharmacologist',                    category: 'Pharmaceutical', subcategory: 'Research & Development' },
  { title: 'Clinical Research Associate',       category: 'Pharmaceutical', subcategory: 'Research & Development' },
  { title: 'Medical Affairs Manager',           category: 'Pharmaceutical', subcategory: 'Commercial' },
  { title: 'Regulatory Affairs Manager',        category: 'Pharmaceutical', subcategory: 'Regulatory' },
  { title: 'Medical Science Liaison',           category: 'Pharmaceutical', subcategory: 'Commercial' },
  { title: 'Drug Safety Scientist',             category: 'Pharmaceutical', subcategory: 'Pharmacovigilance' },
  { title: 'Pharmacovigilance Specialist',      category: 'Pharmaceutical', subcategory: 'Pharmacovigilance' },
  { title: 'Bioinformatician',                  category: 'Pharmaceutical', subcategory: 'Research & Development' },

];

// ── Cosmos setup ───────────────────────────────────────────────────────────────

const client = new CosmosClient(COSMOS_CONNECTION);
const database = client.database(DB_NAME);
const container = database.container(CONTAINER_NAME);

// ── Progress tracking ──────────────────────────────────────────────────────────

function loadProgress() {
  if (RESUME && fs.existsSync(PROGRESS_FILE)) {
    return new Set(JSON.parse(fs.readFileSync(PROGRESS_FILE, 'utf8')).seeded);
  }
  return new Set();
}

function saveProgress(seededIds) {
  fs.writeFileSync(PROGRESS_FILE, JSON.stringify({ seeded: [...seededIds], ts: new Date().toISOString() }));
}

// ── GPT-4o-mini career generator ───────────────────────────────────────────────

async function generateCareers(batch) {
  const today = new Date().toISOString().slice(0, 10);
  const careerList = batch.map(c => `- ${c.title} (${c.category} / ${c.subcategory})`).join('\n');

  const prompt = `Generate detailed career data for each career listed below.
Return a JSON object: { "careers": [ ...array of career objects... ] }
Each career object must match this EXACT schema (no extra fields):
{
  "id": "kebab-case-slug",
  "title": "Career Title",
  "aliases": ["Alternative Name 1", "Alternative Name 2"],
  "category": "Category",
  "subcategory": "Subcategory",
  "tags": ["tag1", "tag2", "tag3"],
  "soc_uk": "UK SOC 2020 4-digit code or null",
  "onet_us": "US O*NET code e.g. 15-1252.00 or null",
  "salary": {
    "uk": { "starting": 0, "mid": 0, "senior": 0, "expert": 0, "currency": "GBP" },
    "us": { "starting": 0, "mid": 0, "senior": 0, "expert": 0, "currency": "USD" }
  },
  "workforce": {
    "uk": {
      "employed": 0,
      "studying": 0,
      "growthPct5yr": 0.0,
      "growthTrend": "growing|stable|declining",
      "vacancies": 0
    },
    "us": {
      "employed": 0,
      "studying": 0,
      "growthPct5yr": 0.0,
      "growthTrend": "growing|stable|declining",
      "vacancies": 0
    }
  },
  "demand": {
    "uk": 0,
    "us": 0,
    "automationRisk": 0,
    "futureScore": 0,
    "trend": "growing|stable|declining"
  },
  "lifestyle": {
    "environment": "Office|Remote|Hybrid|Field|Clinical|Outdoor|Studio|Workshop",
    "stress": 0,
    "energy": 0,
    "collaboration": 0,
    "remoteScore": 0,
    "typicalHours": "9-5|Shifts|Variable|On-call|Freelance"
  },
  "identity": {
    "summary": "2-sentence description of what this role involves day-to-day.",
    "traits": ["Trait 1", "Trait 2", "Trait 3"],
    "strengths": ["Strength 1", "Strength 2"],
    "weaknesses": ["Challenge 1", "Challenge 2"]
  },
  "pathway": {
    "entryRequirements": ["Requirement 1"],
    "qualifications": ["Qualification 1"],
    "skills": ["Skill 1", "Skill 2", "Skill 3"],
    "timeToJunior": "0-6 months|6-12 months|1-2 years",
    "timeToMid": "2-4 years",
    "timeToSenior": "5-8 years",
    "timeToExpert": "10+ years",
    "learningPath": ["Step 1", "Step 2", "Step 3"]
  },
  "salaryLastUpdated": "${today}",
  "lastUpdated": "${today}",
  "source": "seed-v1",
  "confidence": 0.85
}

Rules:
- All scores (demand uk/us, automationRisk, futureScore, stress, energy, collaboration, remoteScore) = integers 0-100
- Salary = realistic annual figures in GBP (UK) and USD (US)
- workforce.employed = estimated total employed in that country (integer, e.g. 120000)
- workforce.studying = estimated people in training/education for this role (integer)
- workforce.growthPct5yr = projected 5-year employment growth as decimal (e.g. 8.5 = 8.5%)
- workforce.vacancies = estimated annual job openings (integer)
- Return ONLY the JSON object, no markdown, no explanation

Careers:
${careerList}`;

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${OPENAI_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      temperature: 0.2,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: 'You are a career data expert with knowledge of ONS, BLS, and industry workforce data. Return valid JSON only.' },
        { role: 'user', content: prompt },
      ],
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`OpenAI ${res.status}: ${err.slice(0, 200)}`);
  }

  const data = await res.json();
  const content = JSON.parse(data.choices[0].message.content);
  return content.careers ?? (Array.isArray(content) ? content : Object.values(content)[0]);
}

// ── Main seed loop ─────────────────────────────────────────────────────────────

async function seed() {
  const seededIds = loadProgress();
  const remaining = CAREERS.filter(c => !seededIds.has(c.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')));

  console.log(`\n🚀 Career Seed — ${CAREERS.length} total, ${remaining.length} to process\n`);

  let seeded = 0;
  let failed = 0;

  for (let i = 0; i < remaining.length; i += BATCH_SIZE) {
    const batch = remaining.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;
    const totalBatches = Math.ceil(remaining.length / BATCH_SIZE);

    process.stdout.write(`[${batchNum}/${totalBatches}] ${batch.map(c => c.title).join(', ')} ... `);

    try {
      const careers = await generateCareers(batch);

      for (const career of careers) {
        if (!career.id) career.id = career.title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        if (!career.category) {
          const match = batch.find(b => b.title === career.title);
          career.category = match?.category ?? 'General';
          career.subcategory = match?.subcategory ?? '';
        }
        await container.items.upsert(career);
        seededIds.add(career.id);
        seeded++;
      }

      saveProgress(seededIds);
      console.log(`✅ ${careers.length} done`);
    } catch (err) {
      console.log(`❌ ${err.message}`);
      failed += batch.length;
    }

    if (i + BATCH_SIZE < remaining.length) {
      await new Promise(r => setTimeout(r, DELAY_MS));
    }
  }

  console.log(`\n✅ Complete — ${seeded} upserted, ${failed} failed`);
  console.log(`📊 Total in Cosmos: ~${seededIds.size} careers`);
  if (failed > 0) console.log(`💡 Re-run with --resume to retry failed batches\n`);
}

seed().catch(console.error);
