name: Deploy product.percentile.one

on:
  push:
    branches:
      - main
    paths:
      - 'src/p1-product/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/p1-product/package-lock.json

      - name: Install dependencies
        working-directory: src/p1-product
        run: npm ci

      - name: Build
        working-directory: src/p1-product
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: src/p1-product/dist
          output_location: ''
          skip_app_build: true
